parallel_task:
  name: "Parallel Execution of Tasks"
  container:
    matrix:
      - image: node:latest
      - image: node:lts
  test_script: sleep 300

docker_build_task:
  name: "Build Docker Image"
  container:
    image: gcr.io/kaniko-project/executor
  build_script: docker build .
  
task:
  name: "Staging Deploy"
  container:
    image: docker:latest
  trigger_type: manual

